/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_llbit_math_bvh_BinaryBVH */

#ifndef _Included_se_llbit_math_bvh_BinaryBVH
#define _Included_se_llbit_math_bvh_BinaryBVH
#ifdef __cplusplus
extern "C" {
#endif
#undef se_llbit_math_bvh_BinaryBVH_SPLIT_LIMIT
#define se_llbit_math_bvh_BinaryBVH_SPLIT_LIMIT 4L
/*
 * Class:     se_llbit_math_bvh_BinaryBVH
 * Method:    closestIntersection
 * Signature: (DDDDDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_se_llbit_math_bvh_BinaryBVH_closestIntersection
  (JNIEnv *, jobject, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jlong);
JNIEXPORT void JNICALL Java_se_llbit_math_bvh_BinaryBVH_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
